version: '3.5'
services:
    vue-ui:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
        - "8081:8080"
        container_name: vue-ui
        volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules