version: '3.5'
services:
    vue-ui-docente:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
        - "8082:8080"
        container_name: vue-ui-docente
        volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules