name: Docker Build and Push

on:
  push:
    # Para que se ejecute solo al hacer un push a main
    branches: [ main ]
    
  workflow_dispatch:

jobs:

  Docker-Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
      - name: Docker build
        run: |
          docker build -t lucaspintos909/docente-frontend:latest -f Dockerbuild .
          
      - name : Docker Push
        run: |
          docker push lucaspintos909/docente-frontend
